name: Build and Test on Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make cmake libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: List files for debug
      run: ls -R
      working-directory: src

    - name: Build main and tests
      working-directory: src
      run: |
        make
        make test

    - name: Run tests
      working-directory: src
      run: ./circular_list_test
